In [1]:
import gym
import robo_gym
from robo_gym.wrappers.exception_handling import ExceptionHandling

In [2]:
target_machine_ip = 'localhost' # or other machine 'xxx.xxx.xxx.xxx'

# initialize environment
env = gym.make('CubeRoomOnNavigationStack-v0', ip=target_machine_ip, gui=True)
env = ExceptionHandling(env)

env.reset(**{'new_room': True, 'new_agent_pose': True})


Starting new Robot Server | Tentative 1
Successfully started Robot Server at localhost:42527


/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


{'occupancy_grid': array([-1, -1, -1, ..., -1, -1, -1], dtype=int16),
 'agent_pose': array([ 4.47545209e-16, -1.69515132e+00,  0.00000000e+00])}

In [5]:
import numpy as np
import copy

import robo_gym_server_modules.robot_server.client as rs_client
from robo_gym.envs.simulation_wrapper import Simulation
from robo_gym_server_modules.robot_server.grpc_msgs.python import robot_server_pb2

from robo_gym.envs.mir_nav.mir_nav import Mir100NavEnv

In [6]:
class TestSim(Simulation):
    cmd = "roslaunch task_on_nav_robot_server sim_robot_server.launch"
    def __init__(self, ip=None, lower_bound_port=None, upper_bound_port=None, gui=False, **kwargs):
        Simulation.__init__(self, self.cmd, ip, lower_bound_port, upper_bound_port, gui, **kwargs)
        rs_address=self.robot_server_ip
        self.client = rs_client.Client(rs_address)

ts = TestSim(ip='localhost', gui=True)
client = ts.client

map_size = 256

rs_state_a = np.zeros([(map_size**2)*2 + 17])

ignore_start = 1
map_state_len = (map_size**2)*2
ignore_len = map_state_len + 6
ignore_index = ignore_start + ignore_len

rs_state_a[0] = map_size
rs_state_a[ignore_index] = 1
rs_state_a[ignore_index+1] = 1
rs_state_a[ignore_index+2] = 10
rs_state_a[ignore_index+3] = 0.4
rs_state_a[ignore_index+4] = 0.2
rs_state_a[ignore_index+5] = 8
rs_state_a[ignore_index+6] = 36
rs_state_a[ignore_index+7] = 40
rs_state_a[ignore_index+8] = 0.8
rs_state_a[ignore_index+9] = 0.15

state_msg = robot_server_pb2.State(state=rs_state_a)

if not client.set_state_msg(state_msg):
    raise Exception('fuuu')

rs_state = np.array(client.get_state_msg().state)
print(rs_state)

Starting new Robot Server | Tentative 1
Successfully started Robot Server at localhost:39961
[256.          -1.          -1.         ...  -0.86143214   2.78691292
   0.        ]


In [8]:
rs = copy.deepcopy(rs_state_a)

rs[ignore_index] = 0
rs[ignore_index+1] = 0
state_msg = robot_server_pb2.State(state=rs)
client.set_state_msg(state_msg)

True

In [9]:
rs_state[map_state_len+1:map_state_len+4]

array([ 1.15682638,  0.07753576, -0.68888658])

In [15]:
client.send_action([0,0,np.pi/4])

True

In [4]:
rs_state = np.array(client.get_state_msg().state)

In [7]:
from PIL import Image

arr = np.array(rs_state[1:1+map_size**2])
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))

arr[arr == 0] = 255
arr[arr == 100] = 0
arr[arr == -1] = 0
arr = np.array(arr, dtype=np.uint8)
unique, counts = np.unique(arr, return_counts=True)
print(dict(zip(unique, counts)))
imgg = Image.fromarray(arr.reshape((256,256)).T, 'L')
imgg.show()

ar = np.array(rs_state[2+map_size**2:1+(map_size**2)*2+1],dtype=np.uint8)
unique, counts = np.unique(ar, return_counts=True)
print(dict(zip(unique, counts)))
img = Image.fromarray(ar.reshape((256,256)).T, 'L')
img.show()

{-1.0: 59713, 0.0: 5333, 100.0: 490}
{0: 60203, 255: 5333}
{0: 50518, 254: 1, 255: 15017}


In [8]:
import numpy as np

g = np.reshape([1,1,1], (3,1))
g.flatten(), g

(array([1, 1, 1]),
 array([[1],
        [1],
        [1]]))

256.0